app/app/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from crawlzero import views

urlpatterns = [
    path('rajesh/', admin.site.urls),
    url(r'^$',views.index,name='index'),
    url(r'^special/',views.special,name='special'),
    url(r'^crawlzero/',include('crawlzero.urls')),
    url(r'^logout/$', views.user_logout, name='logout'),
]

app/crawlzero/urls.py
from django.conf.urls import url
from crawlzero import views
# SET THE NAMESPACE!
app_name = 'crawlzero'
# Be careful setting the name to just /login use userlogin instead!
urlpatterns=[
    url(r'^register/$',views.register,name='register'),
    url(r'^user_login/$',views.user_login,name='user_login'),
    url(r'^upload_file/$',views.upload_file,name='upload_file'),
    
]

app/crawlzero/models.py
from django.db import models
import os
from django.contrib.auth.models import User
import uuid
from django.db.models.signals import post_delete, pre_save
from django.dispatch import receiver

# Create your models here.

def user_directory_path(instance, filename):
    ext = filename.split('.')[-1]
    filename = '{}.{}'.format(uuid.uuid4().hex[:10], ext)
    return os.path.join(str(instance.id), filename)

class File(models.Model):
    #owner = models.OneToOneField  (User, on_delete=models.CASCADE)
    file = models.FileField(upload_to=user_directory_path)

def __str__(self):
  return self.user.username

@receiver(models.signals.post_delete, sender=File)
def auto_delete_file_on_delete(sender, instance, **kwargs):
    if instance.file:
        if os.path.isfile(instance.file.path):
            os.remove(instance.file.path)
@receiver(pre_save, sender=File)
def auto_delete_file_on_change(sender, instance, **kwargs):
    if not instance.pk:
        return False
    try:
        old_file = sender.objects.get(pk=instance.pk).file
    except sender.DoesNotExist:
        return False
    new_file = instance.file
    if not old_file == new_file:
        if os.path.isfile(old_file.path):
            os.remove(old_file.path)

app/crawlzero/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import File


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(), min_length=8)
    firstname = forms.CharField(widget=forms.TextInput)
    lastname = forms.CharField(widget=forms.TextInput)
    email = forms.EmailField(widget=forms.TextInput, required=True)
    class Meta():
        model = User
        fields = ('firstname', 'lastname', 'username','password','email')

    def clean(self):
       username = self.cleaned_data.get('username')
       email = self.cleaned_data.get('email')
       if User.objects.filter(username=username).exists():
            raise forms.ValidationError("Username already exists")
       if User.objects.filter(email=email).exists():
            raise forms.ValidationError("Email already exists")
       return self.cleaned_data

class FileUploadModelForm(forms.ModelForm):
    class Meta:
        model = File
        fields = ('file',) 

    def clean_file(self):
        file = self.cleaned_data['file']
        ext = file.name.split('.')[-1].lower()
        if ext not in ["xls", "csv", "xlsx"]:
            raise forms.ValidationError("Only xls, csv and xlsx files are allowed.")
        # return cleaned data is very important.
        return file

app/crawlzero/views.py
from django.shortcuts import render, redirect
from crawlzero.forms import UserForm, FileUploadModelForm
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import cache_control
from django.contrib import messages
import os
from .models import File
from .scrap import Scraper

# Create your views here.
scraper_obj = Scraper()

def index(request):
    return render(request,'crawlzero/index.html')

@login_required
def special(request):
    return HttpResponse("You are logged in !")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        
        if user_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            newuser = authenticate(username=user_form.cleaned_data['username'], password=user_form.cleaned_data['password'])
            login(request, newuser)
            return HttpResponseRedirect(reverse('index'))
        else:
            print(user_form.errors)
    else:
        user_form = UserForm()
    return render(request,'crawlzero/registration.html',
                          {'user_form':user_form,
                           'registered':registered})

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Your account was inactive.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login details given")
    else:
        return render(request, 'crawlzero/login.html', {})

@login_required
def upload_file(request):
    if request.method == 'POST':
        form = FileUploadModelForm(request.POST, request.FILES)
        if form.is_valid():
            infile = form.save(commit=False)
            infile.user = request.user
            infile.save()
            outfile = scraper_obj.parser(request.FILES['file'])
            infile.delete()
            response = HttpResponse(outfile, content_type='application/vnd.ms-excel')
            response['Content-Disposition'] = 'attachment; filename="updated.xls"'
            return response
            #return render(request, 'crawlzero/login.html', {})
        else:
            return HttpResponse('Upload a csv or excel file')
    else:
        form = FileUploadModelForm()

        
    return render(request, 'crawlzero/upload.html', {'form': form})

app/templates/crawlzero/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>CrawlZero</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
  <body>
    <!--<nav class="navbar navbar-dark bg-dark" style="background-color: #2064a3;"></nav>-->
    <nav class="navbar navbar-default navbar-static-top" style="background-color: #070707;" style="color: #f6f8fa">
      <div class="container">
        <ul class="nav navbar-nav" >
        {# Django Home Link / Admin Link / Register Link#}
          <li><a class="navbar-brand" href="{% url 'index' %}">CrawlZero</a></li>
              
          {# Some logic on what to display for last item#}
          {% if user.is_authenticated %}
            <li><a href="{%url 'crawlzero:upload_file' %}">Upload</a></li>
            <li><a href="{% url 'logout' %}">Logout</a></li>
          {% else %}
            <li><a class="navbar-link" href="{% url 'crawlzero:register' %}">Register</a></li> 
            <li><a class="navbar-link" href="{% url 'crawlzero:user_login' %}">Login</a></li>
          {% endif %}
        </ul>
      </div>
    </nav>
    <div class="container">
    {% block body_block %}
    {% endblock %}

    {% block reg_block %}
    {% endblock %}
    </div>
  </body>
</html>

app/templates/crawlzero/index.html
{% extends "crawlzero/base.html" %}
{% block body_block %}
<div class="container">
  <div class="jumbotron">
    <h1>Welcome to the CrawlZero !</h1>
    {% if user.is_authenticated %}
        <h2>Hello {{ user.username }}</h2>
    {% else %}
        <h2>Login or Register to Continue.!</h2>
    {% endif %}
  </div> 
</div>
{% endblock %}

app/templates/crawlzero/login.html
{% extends 'crawlzero/base.html' %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      <h1>Login here :</h1>
      <form method="post" action="{% url 'crawlzero:user_login' %}">
        {% csrf_token %}
        {# A more "HTML" way of creating the login form#}
          <label for="username">Username:</label>
          <input type="text" name="username" placeholder="Username">
          <label for="password">Password:</label>
          <input type="password" name="password" placeholder="Password">
          <input type="submit" name="" value="Login">
      </form>
    </div>
  </div>
{% endblock %}

{% block reg_block %}
<div class="container">
  <div class="jumbotron">
    <form method="post" action= "{% url 'crawlzero:register' %}">
      {% csrf_token %}
      <p>If new user register first</p>
      <input type="submit" name="" value="Register">
    </form>
  </div>
</div>
{% endblock %}

app/templates/crawlzero/registration.html
{% extends "crawlzero/base.html" %}
{% load static %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      {% if registered %}
        <h1>Thank you for registering!</h1>
      {% else %}
        <h1>Register Here</h1>
        <h3>Just fill out the form.</h3>
<form enctype="multipart/form-data" action= "{% url 'crawlzero:register' %}" method="POST">
          {% csrf_token %}
          {{ user_form.as_p }}
          {{ profile_form.as_p }}
          <input type="submit" name=""  value="Register">
        </form>
        
      {% endif %}
    </div>
  </div>
{% endblock %}

app/templates/crawlzero/upload.html
{% extends "crawlzero/base.html" %}
{% block body_block %}
<div class="container">
  <div class="jumbotron">
    <h1>Upload your file here...</h1>
    <form method="post" enctype="multipart/form-data" action="{% url 'crawlzero:upload_file' %}">
      {% csrf_token %}
      <label for="file">File:</label>
      <input type="file" name="file">
      <input type="submit" value="Upload">
    </form>
  </div>
</div>
{% endblock %}